name: Java CI/CD with AWS EC2

on:
  push:
    branches:
      - main
      - devops-cicd

env:
  AWS_REGION: ap-south-1
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  EC2_INSTANCE_IP: 13.235.114.103
  APP_NAME: myapp
  JAR_FILE: ordering-api-0.0.1-SNAPSHOT.jar

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
          
      - name: Build with Maven
        run: mvn clean install -Dmaven.test.skip=true

      - name: Deploy to AWS CloudFormation (${{ matrix.environment }}-${{ env.STACK_ID }}) (${{ matrix.region }})
        shell: bash
        run: |
          ls -ltr
          ls -ltr target
        
      - name: Stop running app
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.EC2_INSTANCE_IP }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            sudo systemctl stop ${{ env.APP_NAME }}
        
      - name: Copy JAR to EC2 instance
        uses: appleboy/scp-action@master
        with:
          host: ${{ env.EC2_INSTANCE_IP }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: target/${{ env.JAR_FILE }}
          target: /home/ec2-user/${{ env.JAR_FILE }}
          
      - name: Start app on EC2 instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.EC2_INSTANCE_IP }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            sudo systemctl start ${{ env.APP_NAME }}